# Generated by Django 2.1.7 on 2019-03-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0002_auto_20190312_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceselement',
            name='order_on_website',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
